# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://astonishing-halva-d2c550.netlify.app/'
baseurl: ''
title: 'Leighton Buzzard Chess Club'
description: 'Welcome to Leighton Buzzard Chess Club Website'
permalink: pretty
logo: "/assets/logo.png"
currentseason: 2021-22

# Pagination
paginate: 5
paginate_path: blog/page:num

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/favicon-16x16.png'
  32: '/assets/favicon-32x32.png'

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Our teams
  url: /teams/

# Footer nav
navigation_footer:
# - title: Back to top
#   url: "#top"

# Collections
collections:
  seasons:
    title: Seasons
    output: true
  leagues:
    title: Leagues
    output: true
  matches:
    title: Matches
    output: true
  teams:
    title: Teams
    output: true
  players:
    title: Players
    output: true
  games:
    title: Games
    output: true
# Collection settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
  - scope:
      path: ""
      type: "teams"
    values:
      layout: team # Set the default layout for pages
  - scope:
      path: ""
      type: "games"
    values:
      layout: game # Set the default layout for pages
  - scope:
      path: ""
      type: "matches"
    values:
      layout: match # Set the default layout for pages

fonts:
  preconnect_urls:
  font_urls: