backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    editor:
      preview: false
    files:
      - label: 'Homepage'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Find us'
        name: 'findus'
        file: 'findus.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'relation', collection: 'players', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ] }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'seasons'
    label: 'Seasons'
    label_singular: 'Season'
    folder: '_seasons/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Season name', name: 'title', widget: 'string', hint: "e.g. 2021/22" }
      - { label: 'Beds code', name: 'bedscode', widget: 'string', hint: "e.g. 202122 - this is the code used on the Bedfordshire chess website. Used for autogenerating links to league tables." }

  - name: 'leagues'
    label: 'Leagues'
    label_singular: 'League'
    folder: '_leagues/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'League name', name: 'title', widget: 'string', hint: "e.g. 2021/22" }
      - { label: 'Beds code', name: 'bedscode', widget: 'string', hint: "e.g. BedsDiv1 - this is the code used on the Bedfordshire chess website. Used for autogenerating links to league tables.", required: false }
      - { label: 'Description', name: 'body', widget: 'markdown', required: false }

  - name: 'honours'
    label: 'Honours'
    label_singular: 'Honour'
    folder: '_honours/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: "e.g. 2021/22" }
      - { label: 'Date', name: 'date', widget: 'datetime', time_format: false }
      - { label: 'Team', name: 'team', widget: 'relation', collection: 'teams', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ] }
      - { label: 'Player', name: 'player', widget: 'relation', collection: 'players', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ] }
      - { label: 'Description', name: 'body', widget: 'markdown', required: false }

  - name: 'events'
    label: 'Events'
    label_singular: 'Event'
    folder: '_events/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Event name', name: 'title', widget: 'string', hint: "e.g. 2021/22" }
      - { label: 'Season', name: 'season', widget: 'relation', collection: 'seasons', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Event report', name: 'body', widget: 'markdown', required: false }

  - name: 'teams'
    label: 'Teams'
    label_singular: 'Team'
    folder: '_teams/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Team name', name: 'title', widget: 'string' }
      - { label: 'LB Team?', name: 'lbteam', widget: 'boolean', hint: 'Leave unticked for teams in other clubs.', default: true }
      - { label: 'League(s)', name: 'leagues', widget: 'relation', collection: 'leagues', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ], multiple: true, required: false }
      - { label: 'Team captain', name: 'captain', widget: 'relation', collection: 'players', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Players', name: 'players', widget: 'relation', collection: 'players', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ], multiple: true  }
      - { label: 'About', name: 'body', widget: 'markdown', required: false }

  - name: 'players'
    label: 'Players'
    label_singular: 'Player'
    folder: '_players/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Player name', name: 'title', widget: 'string' }
      - { label: 'Mugshot', name: 'photo', widget: 'image', allow_multiple: false, required: false }
      - { label: 'LB Player', name: 'lbplayer', widget: 'boolean', hint: 'Leave unticked for players in other clubs', default: true }
      - { label: 'Current team', name: 'current_team', widget: 'relation', collection: 'teams', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'ECF Number', name: 'ecf', widget: 'string', hint: 'e.g. "275762L"', required: false }
      - { label: 'Chess.com user', name: 'chesscom', widget: 'string', hint: 'e.g. "domwatson"', required: false }
      - { label: 'LIChess user', name: 'lichess', widget: 'string', hint: 'e.g. "DomWatson"', required: false }
      - { label: 'Bio/Description', name: 'body', widget: 'markdown', required: false }

  - name: 'matches'
    label: 'Matches'
    label_singular: 'Match'
    folder: '_matches/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: 'e.g. Beds Division 2 2021/22: OU Away' }
      - { label: 'Date', name: 'matchdate', widget: 'datetime', time_format: false }
      - { label: 'League', name: 'league', widget: 'relation', collection: 'leagues', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Season', name: 'season', widget: 'relation', collection: 'seasons', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Home team', name: 'hometeam', widget: 'relation', collection: 'teams', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Opponent', name: 'opponent', widget: 'relation', collection: 'teams', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Home or away', name: 'homeaway', widget: 'select', options: [ "Home", "Away" ] }
      - { label: 'Our team', name: 'boards', widget: 'relation', collection: 'players', multiple: true, required: false, hint: 'Add players in board order that represent the home team', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ] }
      - { label: 'Result', name: 'result', widget: 'select', options: [ "TBC", "Win", "Draw", "Loss", "Abandoned" ] }
      - { label: 'Points scored', name: 'score', widget: 'number', min: 1, value_type: "float", step: 0.5, required: false }
      - { label: 'Points available', name: 'scoreavailable', widget: 'number', min: 1, value_type: "int", required: false }
      - { label: 'Match Report', name: 'body', widget: 'markdown', required: false }

  - name: 'games'
    label: 'Games'
    label_singular: 'Game'
    folder: '_games/'
    create: true
    slug: 'game-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: 'e.g. 2022-04-05: Lee Davies vs Dominic Watson' }
      - { label: 'Date', name: 'gamedate', widget: 'datetime', time_format: false }
      - { label: 'Match', name: 'match', widget: 'relation', collection: 'matches', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Board number', name: 'boardno', widget: 'number', required: false,  value_type: "int" }
      - { label: 'Event', name: 'event', widget: 'relation', collection: 'events', required: false, value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'White', name: 'white', widget: 'relation', collection: 'players', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'White rating', name: 'whiterating', widget: 'string', required: false  }
      - { label: 'Black', name: 'black', widget: 'relation', collection: 'players', value_field: '{{slug}}', search_fields: [ 'title' ], display_fields: [ 'title' ]  }
      - { label: 'Black rating', name: 'blackrating', widget: 'string', required: false  }
      - { label: 'Result', name: 'result', widget: 'select', options: [ '?', '1-0', '½-½', '0-1' ] }
      - { label: 'PGN', name: 'pgn', widget: 'text', required: false }
      - { label: 'Game Report', name: 'body', widget: 'markdown', required: false }